version: '3'
services:
  metabase:
    container_name: dafmetabase
    image: metabase/metabase:latest
    links:
        - postgresmetabase
    expose:
      - "3000"
    env_file:
      - env_file
    networks:
      - db_nw
      - web_nw
    depends_on:
      - postgresmetabase
  postgresmetabase:
    container_name: postgresmetabase
    image: postgres:10.6
    ports:
        - "5434:5432"
    env_file:
      - env_file
    networks:
      - db_nw
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - web_nw
    depends_on:
      - metabase
networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
